/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as Collections001RouteImport } from './routes/collections.001'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as ApiPublicBackupImageRouteImport } from './routes/api/public/backup-image'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const Collections001Route = Collections001RouteImport.update({
  id: '/collections/001',
  path: '/collections/001',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBackupImageRoute = ApiPublicBackupImageRouteImport.update({
  id: '/api/public/backup-image',
  path: '/api/public/backup-image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/collections/001': typeof Collections001Route
  '/products/$slug': typeof ProductsSlugRoute
  '/api/public/backup-image': typeof ApiPublicBackupImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/collections/001': typeof Collections001Route
  '/products/$slug': typeof ProductsSlugRoute
  '/api/public/backup-image': typeof ApiPublicBackupImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/shop': typeof ShopRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/collections/001': typeof Collections001Route
  '/products/$slug': typeof ProductsSlugRoute
  '/api/public/backup-image': typeof ApiPublicBackupImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/checkout'
    | '/contact'
    | '/shop'
    | '/admin/leads'
    | '/collections/001'
    | '/products/$slug'
    | '/api/public/backup-image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/checkout'
    | '/contact'
    | '/shop'
    | '/admin/leads'
    | '/collections/001'
    | '/products/$slug'
    | '/api/public/backup-image'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/checkout'
    | '/contact'
    | '/shop'
    | '/admin/leads'
    | '/collections/001'
    | '/products/$slug'
    | '/api/public/backup-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  ShopRoute: typeof ShopRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  Collections001Route: typeof Collections001Route
  ProductsSlugRoute: typeof ProductsSlugRoute
  ApiPublicBackupImageRoute: typeof ApiPublicBackupImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/001': {
      id: '/collections/001'
      path: '/collections/001'
      fullPath: '/collections/001'
      preLoaderRoute: typeof Collections001RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/backup-image': {
      id: '/api/public/backup-image'
      path: '/api/public/backup-image'
      fullPath: '/api/public/backup-image'
      preLoaderRoute: typeof ApiPublicBackupImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  ShopRoute: ShopRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  Collections001Route: Collections001Route,
  ProductsSlugRoute: ProductsSlugRoute,
  ApiPublicBackupImageRoute: ApiPublicBackupImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
